### ISSUE TITLE
needs a logo

### ISSUE THREAD

**Issue by dmd** [bbfrederick/picachooser#3]
You need an absolutely atrocious and therefore non-copyright-infringing logo of a pikachu pointing to a component.

**Comment by bbfrederick** [comment]
I agree, but I can't draw to save my life...  I'll solicit help.

**Comment by bbfrederick** [comment]
Done.

**Comment by dmd** [comment]
You missed the part where it was supposed to be "absolutely atrocious and therefore non-copyright-infringing".
